import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import HeadArticle from '../containers/HeadArticle';
import Header from '../containers/Header';
import ImageArticle from '../containers/ImageArticle';
import LargeImageArticle from '../containers/ImageArticle/Large';
import SmallImageArticle from '../containers/ImageArticle/Small';
import Series from '../containers/Series';
import Sidebar from '../containers/Sidebar';
import Social from '../containers/Social';
import TextArticle from '../containers/TextArticle';
import styles from '../styles/Home.module.sass';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Howard Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header />
        <HeadArticle />
        <ImageArticle />
        <Social />
        <TextArticle />
        <LargeImageArticle />
        <SmallImageArticle />
        <Sidebar />
        <Series />
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Footer
        </a>
      </footer>
    </div>
  );
};

export default Home;
