
name: Frontend Preview Deployment

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  vercel-deploy:
    runs-on: ubuntu-latest
    env:
      VERCEL_TOKEN: ${{secrets.VERCEL_TOKEN}}
      VERCEL_ORG_ID: ${{secrets.VERCEL_ORG_ID}}
      VERCEL_PROJECT_ID: ${{secrets.VERCEL_PROJECT_ID}}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Vercel Preview Deploy
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}