name: Frontend Production Deployment

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  vercel-deploy:
    runs-on: ubuntu-latest
    env:
      VERCEL_TOKEN: ${{secrets.VERCEL_TOKEN}}
      VERCEL_ORG_ID: ${{secrets.VERCEL_ORG_ID}}
      VERCEL_PROJECT_ID: ${{secrets.VERCEL_PROJECT_ID}}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Vercel Production Deploy
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
          vercel-args: "--prod"